"""create_tables

Revision ID: 4d6f18540f41
Revises: 
Create Date: 2024-11-05 11:35:56.123327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4d6f18540f41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_name', 'question_categories', ['category_name'], unique=False)
    op.create_index(op.f('ix_question_categories_category_name'), 'question_categories', ['category_name'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1792), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['question_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question', 'questions', ['question'], unique=False)
    op.create_index('idx_question_vector_hnsw', 'questions', [sa.text('vector vector_ip_ops')], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_index(op.f('ix_questions_question'), 'questions', ['question'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_question'), table_name='questions')
    op.drop_index('idx_question_vector_hnsw', table_name='questions', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_index('idx_question', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_categories_category_name'), table_name='question_categories')
    op.drop_index('idx_category_name', table_name='question_categories')
    op.drop_table('question_categories')
    # ### end Alembic commands ###
