"""add question v2

Revision ID: f1fe6fa2c708
Revises: a1c123cf4fe2
Create Date: 2025-05-20 16:42:14.926915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f1fe6fa2c708'
down_revision: Union[str, None] = 'a1c123cf4fe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions_v2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['question_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_v2_text', 'questions_v2', ['question'], unique=False)
    op.create_index('idx_question_v2_vector_hnsw', 'questions_v2', [sa.text('vector vector_ip_ops')], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64})
    op.create_index(op.f('ix_questions_v2_question'), 'questions_v2', ['question'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_v2_question'), table_name='questions_v2')
    op.drop_index('idx_question_v2_vector_hnsw', table_name='questions_v2', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64})
    op.drop_index('idx_question_v2_text', table_name='questions_v2')
    op.drop_table('questions_v2')
    # ### end Alembic commands ###
