import json
from typing import Dict
from aivc.sop.mindfulness.mf2.common import Mindfulness2StateType
from aivc.sop.common.common import (
    Actions, VoiceSequence, VoiceAction, BgmAction, MediaAction
)


states_dict: Dict[Mindfulness2StateType, Actions] = {
    Mindfulness2StateType.PREPARE: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="我们的大脑,是个走走停停的漫游者",
                    wait_time=2,
                    filename="c4d410c6325ddb35181c224a889c3112.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="如果当下发生的事情,新奇有趣,他就停下来专注的观察,一旦觉得无聊了,就开始在思绪的迷宫中,四处漫游,直到再次被意识呼唤回来",
                    wait_time=2,
                    filename="70fc781aa6290133589ef96e7f170d05.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="近年来神经科学家们,也验证了大脑的这一特点",
                    wait_time=2,
                    filename="d8f0ae594597b55b0e8c3273acdfbb9b.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="原来大脑中有一些特定的区域,叫做大脑默认网络",
                    wait_time=2,
                    filename="2b0c26c7053daa7a8e54a3e4dd23c7a8.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="在注意力集中时,默认网络得到抑制,一旦注意力放松,他就会自发启动,跳到与当下无关的思绪上,比如一会吃什么,昨晚谁说了什么",
                    wait_time=2,
                    filename="33671ee648882781c5299a83b478d787.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="科学家们还发现这种大脑的漫游,比集中注意力,还要消耗远远更多的能量,这也解释了,为什么同样做一件事情,专注让人感到平静,走神非但不会让人感到放松,反而会增添疲惫感",
                    wait_time=2,
                    filename="f186545b9067fbba2c1a0ef61b558b53.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="而正面练习的目的之一,就是,逐渐减少无意识的思绪漫游,让能量能够集中在当下所发生的事情上,让心情也能够放松,和平静下来",
                    wait_time=2,
                    filename="3d1f8ff6d64aab3e39d536d7c3d0b482.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="今天,我们将正式开始学习观呼吸,让呼吸作为注意力的锚点,一旦走神了,就把它拉回原处",
                    wait_time=2,
                    filename="4e27d5514dc75e90b6d5f2817de1c9d9.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="在正式开始之前,我还想邀请你,对自己温柔一点,如果你发现自己走神了,请知道那是大脑默认网络正常的生理活动,千万不必责怪自己,你随时都有机会重新开始,把注意力放到呼吸上",
                    wait_time=4,
                    filename="c3a57f58283d912e4840c126796104f2.mp3"
                )
            ]
        ),        
        bgm=BgmAction(
            action=MediaAction.PLAY,
            filename="金星.mp3",
            volume=50
        ),
    ),
    
    Mindfulness2StateType.MEDITATION1: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="欢迎来到第二天的课程",
                    wait_time=2,
                    filename="ed701383f9cdc697f1b336dc541fc5d7.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="请像昨天一样,找到一个舒适的坐姿",
                    wait_time=2,
                    filename="96e5b628b07747a9d9a934a3340b18b6.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="你可以盘腿而坐,也可以坐在椅子上,请选择任何,让你觉得舒适的姿势,确保让上身能够挺立坐直",
                    wait_time=2,
                    filename="6443499a66d146d1a972d1987b3d4497.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="然后轻轻的闭上双眼",
                    wait_time=2,
                    filename="80ec95104a656a0f2f32566759e24cb9.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="让我们做3个深呼吸,来开始今天的练习",
                    wait_time=2,
                    filename="6a633b1c2a70699548294c6101fdd8b3.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="用鼻子均匀深沉的吸气",
                    wait_time=3,
                    filename="288f90ad9783843ea86be04fd0a7c931.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="再用鼻子缓缓的呼气",
                    wait_time=3,
                    filename="74e6ba58f95e66b24a0983583ff4cdb7.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="深吸气,感受气息,充满身体的所有角落",
                    wait_time=2,
                    filename="c9587cb9a34448566827c8bcb56c1c3c.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="慢慢的呼气,放松下来,允许重力,将身体拉向大地的方向",
                    wait_time=2,
                    filename="ab0380083ee8fca81e3c7dcc8c56503f.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="再做最后一次",
                    wait_time=8,
                    filename="a01f2fbd62a5113fdba4ae9ba3a54561.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.MEDITATION2: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="很好,请从头到脚检查一下,此刻你的身体中,哪里还有紧张感",
                    wait_time=2,
                    filename="df8e92444d901023fc31fda84fd22a2b.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="检查你的眉心",
                    wait_time=2,
                    filename="5106db064a2bb2b72ed43cf69a783b45.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="眼睛周围",
                    wait_time=2,
                    filename="68e17ace8c1491c144006ff11aec9203.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="双肩",
                    wait_time=2,
                    filename="6f99443ce5b410ceaadab732be7ec776.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="双手",
                    wait_time=2,
                    filename="b15691150b849c59ff075f2b3db38c9c.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="试着有意识的,去从头到脚的放松身体",
                    wait_time=5,
                    filename="775f619379bdc5428b11051942a07b7b.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.MEDITATION3: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="现在,请把注意力慢慢放到呼吸上",
                    wait_time=3,
                    filename="ee216f72d0a3e8275a13f871035c6a60.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="去观察此刻你的呼吸,是快还是慢",
                    wait_time=3,
                    filename="53674c56e0b05675c522acae04656121.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="是深还是浅",
                    wait_time=3,
                    filename="670637d73a83e9a4aeb2fad1f195ec9b.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="是吸气长一点,还是呼气长一点",
                    wait_time=15,
                    filename="c22064a54bb8bdf883ccd2ac6441e46f.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.MEDITATION4: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="直到呼吸每时每刻都在变化，每一种呼吸,都有它存在的意义",
                    wait_time=2,
                    filename="290d8350e98fd9dfaaf1307bd094b4ce.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="不需要刻意的控制呼吸,也无需改变它",
                    wait_time=2,
                    filename="f790d9fe5afee93c7607326d0aff5796.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="试着像个旁观者一样,客观的观察,此刻你最自然的呼吸",
                    wait_time=2,
                    filename="424f67c6837d9be6ab0229b906a35406.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="也许你会发现,让你走神的念头有些比较弱",
                    wait_time=27,
                    filename="8716045559cd13422dd5c055e96643d2.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.MEDITATION5: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="在观察呼吸的过程中,你可能也会留意到其他信号,比如外界的声音,你身体的感觉,或脑海中念头的低语声",
                    wait_time=5,
                    filename="1cd5781dab01bdc3d44e09d8cfd34b8c.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="这些都是很正常的,请你像个旁观者一样,简单的意识到他们的存在,无需控制或改变,然后再次把注意力,放回到呼吸的感受上",
                    wait_time=5,
                    filename="23611c562c2221509c9eb32c8d346888.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.MEDITATION6: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="你可以跟着呼吸,在心中默念吸气",
                    wait_time=2,
                    filename="8eb01cc74bc1218ee98231d12920b8b4.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="呼气",
                    wait_time=2,
                    filename="f449961589c329b730e563ef6c028bbb.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="吸气",
                    wait_time=2,
                    filename="56164c5abe49f0169c08ee966dd2d100.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="呼气",
                    wait_time=2,
                    filename="f449961589c329b730e563ef6c028bbb.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="也许你会发现,让你走神的念头有些比较弱",
                    wait_time=60,
                    filename="8716045559cd13422dd5c055e96643d2.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.MEDITATION7: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="也许你会发现,让你走神的念头有些比较弱，在他出现不久你就能够发现",
                    wait_time=2,
                    filename="da2a304f3a1ab0d7340745d505e242cc.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="而有些念头很强,它能够把你带走很久,甚至让你忘记,自己坐在这里是干什么的,请知道这些都非常正常,你可以借助我的声音,来打断走神，也可以做一个深呼吸,或者睁开眼睛,等到注意力稳定了,再继续练习",
                    wait_time=4,
                    filename="52585edad07ff2046b51f572da48459e.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.MEDITATION8: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="请再次调整一下坐姿",
                    wait_time=2,
                    filename="a7cab83cf5a38edc2a89fd90f99bd453.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="提醒自己,让脊柱自然的向上空延展",
                    wait_time=2,
                    filename="98a923fd689d4ceb06ea74bafc0e60bb.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="放松面部表情",
                    wait_time=2,
                    filename="2f6bb861419f3a1305e3d3dc2f39cdb5.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="也试着,更加耐心和温柔的对待自己",
                    wait_time=26,
                    filename="2875e839f38fea39c3d9517b33ab3411.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.MEDITATION9: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="在最后的一分钟时间内,你不再需要去观察呼吸，请放下一切技巧,任由身心在此放松",
                    wait_time=50,
                    filename="0823ed780c24a6739d821a1945884db7.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.MEDITATION10: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="非常好,恭喜你,完成了第二节正面练习",
                    wait_time=2,
                    filename="dfa841ed9646020f100f836f81d47bd8.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="在刚才的练习中,你是否体验到了大脑漫游,这种走神的现象",
                    wait_time=2,
                    filename="d01ff96e8d516ae422daa0c53c0c88ee.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="其实杂念本身不是问题,问题是走神,让我们偏离了,想要专注的事物,不知不觉间,消耗掉有限的精力,不过不用着急,我们可以从简单的觉察走神开始,慢慢的改变应对它的方法,从而不再被杂念牵着鼻子走",
                    wait_time=4,
                    filename="7a0d01821234e6ad7294e1280be1530a.mp3"
                )
            ]
        )
    ),
    
    Mindfulness2StateType.END: Actions(
        action_feature="",
        voice=VoiceSequence(
            voices=[
                VoiceAction(
                    action="play",
                    text="请慢慢的睁开双眼",
                    wait_time=2,
                    filename="6e1a00c58637ab2a65d91a9738699bf4.mp3"
                ),
                VoiceAction(
                    action="play",
                    text="我在第3节课中等你",
                    wait_time=2,
                    filename="5517f31a22d428f65047f82fbfdc1588.mp3"
                )
            ]
        )
    )
}
